🧰 Dependency:
  - changed-files:
      - any-glob-to-any-file: 'package-lock.json'

📚 Documentation:
  - changed-files:
      - any-glob-to-any-file: ['README.md', 'docs/**']

⚖️ Legal:
  - changed-files:
      - any-glob-to-any-file: 'LICENSE'

🔖 Release:
  - changed-files:
      - any-glob-to-any-file: 'CHANGELOG.md'

🧪 Testing:
  - changed-files:
      - any-glob-to-any-file: '**/*.test.ts'

🛠️ Tooling:
  - changed-files:
      - any-glob-to-any-file:
          [
            '.changeset/**',
            '.claude/**',
            '.github/**',
            '.vscode/**',
            '.zed/**',
            '.editorconfig',
            '.*ignore',
            '.nvmrc',
            '.ox*.json',
            'config/**',
            '*.config.*',
            'package*.json',
            'tsconfig*.json',
          ]
